# Generated by Django 4.2.15 on 2024-08-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="review_sum",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
