# Generated by Django 4.2.15 on 2024-09-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_semi_comp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=150, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="contact_address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
