# Generated by Django 4.2.15 on 2024-09-30 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="matching_history",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
