# Generated by Django 4.2.15 on 2024-10-05 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="matching_history",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
