# Generated by Django 4.2.15 on 2024-10-21 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0003_dailyusercount"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyusercount",
            name="date",
            field=models.DateField(default=datetime.date(2024, 10, 21), unique=True),
            preserve_default=False,
        ),
    ]
